spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youlexuandb?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    solr:
      host: http://192.168.188.128:8088/solr
      repositories:
        enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.offcn.demo.pojo
dubbo:
  application:
    name: demo03
  registry:
    address: zookeeper://192.168.188.128:2181
  protocol:
    port: 20881 #该参数默认20880
#  monitor:
#    address: 监控中心地址，如果注册中心和监控中心在同一台服务器上，可以省略该参数